In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import math
%matplotlib inline
from sklearn import preprocessing
import statsmodels.formula.api as smf
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

pd.options.display.float_format = '{:.3f}'.format

The following dataset displays charateristics commonly used in diagnosing breast cancer. The dataset was taken from http://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+%28Original%29.

In [5]:
df = pd.read_csv('C:\\Users\\cocob\\Documents\\breast-cancer-wisconsin.csv')

## Data Description

In [3]:
df.head()

ID  Clump_Thickness  UniformityofCellSize  UniformityofCellShape  \
0  1000025                5                     1                      1   
1  1002945                5                     4                      4   
2  1015425                3                     1                      1   
3  1016277                6                     8                      8   
4  1017023                4                     1                      1   

   Marginal_Adhesion  SingleEpithelial_CellSize BareNuclei  BlandChromatin  \
0                  1                          2          1               3   
1                  5                          7         10               3   
2                  1                          2          2               3   
3                  1                          3          4               3   
4                  3                          2          1               3   

   NormalNucleoli  Mitoses  Class  
0               1        1      2  
1               2        1      2  
2               1        1      2  
3               7        1      2  
4               1        1      2

### Random Forrest

In [4]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

In [6]:
rfc = ensemble.RandomForestClassifier()
X = df.drop('Class', 1)
Y = df['Class']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.91549296, 0.95714286, 0.97142857, 0.9       , 0.97142857,
       0.94285714, 0.94285714, 1.        , 0.98550725, 0.98550725])

In [7]:
# Create training and test sets.
offset = int(X.shape[0] * 0.9)

# Put 90% of the data in the training set.
X_train, y_train = X[:offset], Y[:offset]

# And put 10% in the test set.
X_test, y_test = X[offset:], Y[offset:]

In [8]:
rf = rfc.fit(X_train, y_train)

In [9]:
predict_train = rf.predict(X_train)

In [10]:
y_test_pred = rf.predict(X_test)

In [11]:
table_train = pd.crosstab(y_train, predict_train, margins=True)
table_test = pd.crosstab(y_test, y_test_pred, margins=True)

In [12]:
cross_val_score(rf, X_train, y_train, cv=10)

array([0.890625  , 0.95238095, 0.96825397, 0.92063492, 0.93650794,
       0.96825397, 0.93650794, 0.98412698, 0.98387097, 0.98387097])

In [13]:
cross_val_score(rf, X_train, y_train, cv=10).mean()

0.9492535522273424

In [14]:
cross_val_score(rf, X_test, y_test, cv=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])